spring.application.name=demo
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
jwt.secret=${JWT_SECRET}
app.cors.allowed-origins=http://localhost:4200,https://journal-app-iota-green.vercel.app